name: train1
root: ../dataset
type: cross-domain
domain: [ff, cdf]
real_dataset_names: [FaceForensics++, Celeb-DF-v2, deepfacelab, stargan, styleclip, heygen_new]
fake_dataset_names: [deepfacelab, StyleGAN2, fsgan, faceswap, stargan, styleclip, heygen, heygen_new]
batch_size: 128
workers: 16
balance: true
sample_per_class: 400
split:
  train: 0.7
  val: 0.1
  test: 0.2
