name: All42Batch32
root: ../dataset
type: cross-domain
domain: [ff, cdf]
real_dataset_names: [FaceForensics++, Celeb-DF-v2, deepfacelab, heygen_new, stargan, styleclip, CollabDiff, MidJourney]
fake_dataset_names: [deepfacelab, heygen_new, stargan, styleclip, CollabDiff, MidJourney, DiT, fsgan, lia, StyleGAN2, faceswap, heygen, simswap, blendface, danet, ddim, e4s, facedancer, fomm, hyperreenact, inswap, mcnet, mobileswap, MRAA, one_shot_free, pirender, RDDM, simswap, SiT]
batch_size: 32
workers: 16
balance: true
sample_per_class: 1000
split:
  train: 0.9
  val: 0.1
  test: 0.0
